The-Sculptor/Server

- src/main/java/Backend/sculptor/User/Entity/Users.java
- src/main/java/Backend/sculptor/User/Repository/UserRepository.java
[refact] Users 엔티티 리팩토링
---
Users 관련 파일들이 Member 패키지 아래에 들어가있어서 수정했습니다!
---
kimin
---
> [refact] Users 엔티티 리팩토링

- src/main/java/Backend/sculptor/Stone/Entity/Achieve.java
- src/main/java/Backend/sculptor/Stone/Entity/AchieveStatus.java
- src/main/java/Backend/sculptor/Stone/Entity/Stone.java
> [feat] achieve 엔티티 생성

- src/main/java/Backend/sculptor/User/Entity/Users.java
is_public 필드의 default 값 설정
---
is_public 는 기본값으로 true를 가지도록 수정하였습니다.
---
kimin
---
> [refact] 계정 공개 여부(is_public) 필드 deafult 값 true로 설정

- src/main/java/Backend/sculptor/APIResponse/APIBody.java
- src/main/java/Backend/sculptor/Stone/Controller/StoneController.java
- src/main/java/Backend/sculptor/Stone/DTO/StoneDTO.java
- src/main/java/Backend/sculptor/Stone/Repository/StoneRepository.java
- src/main/java/Backend/sculptor/Stone/Service/StoneService.java
> [feat] <공방> stones 전체 조회 기능 추가_성공로직만 & api response 공통 테마 작성

- src/main/java/Backend/sculptor/User/Controller/UserController.java
- src/main/java/Backend/sculptor/User/Service/UserService.java
회원탈퇴 기능 구현
---
회원 탈퇴 기능을 구현했습니다.
---
kimin
---
> [feat] 회원탈퇴 api 구현

- src/main/java/backend/sculptor/domain/museum/controller/MuseumController.java
- src/main/java/backend/sculptor/domain/museum/dto/Museum.java
- src/main/java/backend/sculptor/domain/museum/dto/MuseumDetail.java
- src/main/java/backend/sculptor/domain/museum/service/MuseumDetailService.java
- src/main/java/backend/sculptor/domain/museum/service/MuseumService.java
- src/main/java/backend/sculptor/domain/stone/entity/Stone.java
- src/main/java/backend/sculptor/domain/stone/service/StoneService.java
> [feat] 박물관 계층 구현

- src/main/java/backend/sculptor/domain/stone/controller/AchieveController.java
- src/main/java/backend/sculptor/domain/stone/dto/AchieveDTO.java
- src/main/java/backend/sculptor/domain/stone/dto/SculptorResultDTO.java
- src/main/java/backend/sculptor/domain/stone/dto/StoneAchievesListDTO.java
- src/main/java/backend/sculptor/domain/stone/dto/StoneDetailDTO.java
- src/main/java/backend/sculptor/domain/stone/dto/StoneSculptRequest.java
- src/main/java/backend/sculptor/domain/stone/entity/Achieve.java
- src/main/java/backend/sculptor/domain/stone/entity/Stone.java
- src/main/java/backend/sculptor/domain/stone/repository/AchieveRepository.java
- src/main/java/backend/sculptor/domain/stone/repository/StoneRepository.java
- src/main/java/backend/sculptor/domain/stone/service/AchieveScheduledTask.java
- src/main/java/backend/sculptor/domain/stone/service/AchieveService.java
- src/main/java/backend/sculptor/domain/stone/service/StoneService.java
- src/main/java/backend/sculptor/global/config/SchedulerConfig.java
---
돌 상태 변하는 것만 하면 됩니다.
(이끼...)
---
---
> Soyeon 공방 전체 완성

- src/main/java/backend/sculptor/domain/follow/repository/FollowRepository.java
- src/main/java/backend/sculptor/domain/follow/service/FollowService.java
- src/main/java/backend/sculptor/domain/museum/controller/MuseumController.java
- src/main/java/backend/sculptor/domain/museum/dto/MuseumDTO.java
- src/main/java/backend/sculptor/domain/museum/service/MuseumDetailService.java
- src/main/java/backend/sculptor/domain/museum/service/MuseumService.java
- src/main/java/backend/sculptor/domain/user/entity/Users.java
- src/main/java/backend/sculptor/global/oauth/annotation/CurrentUserArgumentResolver.java
---
박물관 api를 위한 한 줄 소개, 팔로잉 팔로우 수 추가
---
---
#33
> [feat] 박물관 기능 추가

- src/main/java/backend/sculptor/domain/stone/service/StoneService.java
> [refact] 공방 전체 3차 완성

- src/main/java/backend/sculptor/domain/stone/controller/StoneController.java
> [refact]균열 메꾸기 컨트롤러 메세지 수정

- src/main/java/backend/sculptor/domain/comment/dto/CommentDTO.java
- src/main/java/backend/sculptor/domain/comment/entity/CommentLike.java
- src/main/java/backend/sculptor/domain/comment/repository/CommentLikeRepository.java
- src/main/java/backend/sculptor/domain/comment/service/CommentLikeService.java
- src/main/java/backend/sculptor/domain/comment/service/CommentService.java
- src/main/java/backend/sculptor/domain/follow/controller/FollowController.java
- src/main/java/backend/sculptor/domain/follow/repository/FollowRepository.java
- src/main/java/backend/sculptor/domain/follow/service/FollowService.java
- src/main/java/backend/sculptor/domain/museum/controller/MuseumController.java
- src/main/java/backend/sculptor/domain/museum/dto/MuseumDTO.java
- src/main/java/backend/sculptor/domain/museum/dto/MuseumDetailDTO.java
- src/main/java/backend/sculptor/domain/museum/service/MuseumDetailService.java
- src/main/java/backend/sculptor/domain/museum/service/MuseumService.java
- src/main/java/backend/sculptor/domain/stone/service/StoneService.java
- src/main/java/backend/sculptor/domain/user/entity/Users.java
- src/main/java/backend/sculptor/global/exception/BadRequestException.java
- src/main/java/backend/sculptor/global/exception/ErrorCode.java
- src/main/java/backend/sculptor/global/exception/GlobalExceptionHandler.java
- src/main/java/backend/sculptor/global/exception/NotFoundException.java
- src/main/java/backend/sculptor/global/oauth/annotation/CurrentUserArgumentResolver.java
> [feat] 박물관에서 목표일 이후의 날짜만 조회, 방명록 좋아요 기능

- .gitignore
> [refact].gitignore .jar 주석 해제

- .gitignore
> [refact] .gitignore .gradle 주석

- build.gradle
- src/main/resources/application.yml
> Soyeon mysql 세팅

- src/test/java/backend/sculptor/domain/SculptorApplicationTests.java
> [refact]SculptorApplicaionTests @Disabled

- src/main/resources/application.yml
application-oauth 추가
---
application.yml 에 oauth 가 include 되어 있지 않아있어서 추가했습니다!
---
kimin
---
> [refact] application-oauth 추가

- src/main/resources/application-oauth.yml
> [refact] 카카오 redirect uri 재설정

- src/main/java/backend/sculptor/domain/comment/dto/CommentDTO.java
- src/main/java/backend/sculptor/domain/comment/dto/CommentLikeDTO.java
- src/main/java/backend/sculptor/domain/comment/entity/Comment.java
- src/main/java/backend/sculptor/domain/comment/entity/CommentLike.java
- src/main/java/backend/sculptor/domain/comment/service/CommentService.java
- src/main/java/backend/sculptor/domain/museum/controller/MuseumController.java
- src/main/java/backend/sculptor/domain/museum/dto/MuseumDTO.java
- src/main/java/backend/sculptor/domain/museum/dto/MuseumDetailDTO.java
- src/main/java/backend/sculptor/domain/museum/service/MuseumDetailService.java
- src/main/java/backend/sculptor/domain/museum/service/MuseumService.java
- src/main/java/backend/sculptor/domain/stone/service/AchieveService.java
> [feat] 박물관 기능 구현

- src/main/java/backend/sculptor/global/oauth/handler/CustomAuthenticationSuccessHandler.java
> [refact] 로그인 json 확인

- src/main/java/backend/sculptor/global/oauth/handler/CustomAuthenticationSuccessHandler.java
> [refact] 로그인 json 확인.

- src/main/java/backend/sculptor/domain/museum/controller/MuseumController.java
- src/main/java/backend/sculptor/domain/museum/dto/MuseumProfileDTO.java
- src/main/java/backend/sculptor/domain/museum/service/MuseumProfoileService.java
- src/main/java/backend/sculptor/domain/museum/service/MuseumService.java
- src/main/java/backend/sculptor/domain/stone/service/StoneService.java
- src/main/java/backend/sculptor/domain/user/entity/Users.java
- src/main/java/backend/sculptor/global/exception/ErrorCode.java
---
박물관 프로필 기능 추가
---
---
close #32
> [feat] 박물관 프로필 기능 추가

- src/main/java/backend/sculptor/domain/comment/entity/Comment.java
- src/main/java/backend/sculptor/domain/comment/entity/CommentLike.java
- src/main/java/backend/sculptor/domain/comment/service/CommentLikeService.java
- src/main/java/backend/sculptor/domain/comment/service/CommentService.java
- src/main/java/backend/sculptor/domain/follow/controller/FollowController.java
- src/main/java/backend/sculptor/domain/follow/dto/FollowSimpleListDto.java
- src/main/java/backend/sculptor/domain/follow/entity/Follow.java
- src/main/java/backend/sculptor/domain/follow/repository/FollowRepository.java
- src/main/java/backend/sculptor/domain/follow/service/FollowService.java
- src/main/java/backend/sculptor/domain/home/controller/HomeController.java
- src/main/java/backend/sculptor/domain/museum/controller/MuseumController.java
- src/main/java/backend/sculptor/domain/museum/dto/MuseumDetailDTO.java
- src/main/java/backend/sculptor/domain/museum/service/MuseumDetailService.java
- src/main/java/backend/sculptor/domain/stone/dto/StoneLikeDTO.java
- src/main/java/backend/sculptor/domain/stone/entity/Stone.java
- src/main/java/backend/sculptor/domain/stone/entity/StoneLikes.java
- src/main/java/backend/sculptor/domain/stone/service/AchieveService.java
- src/main/java/backend/sculptor/domain/stone/service/StoneLikeService.java
- src/main/java/backend/sculptor/domain/stone/service/StoneService.java
- src/main/java/backend/sculptor/domain/user/entity/Users.java
> [feat] 부모-자식 연관관계 매핑

- src/main/java/backend/sculptor/domain/home/controller/HomeController.java
> [refact] 홈 컨트롤러 팔로우 없을때 200OK 로 수정

- src/main/java/backend/sculptor/domain/follow/service/FollowService.java
- src/main/java/backend/sculptor/domain/museum/controller/MuseumController.java
- src/main/java/backend/sculptor/domain/museum/dto/MuseumDetailDTO.java
- src/main/java/backend/sculptor/domain/museum/service/MuseumProfoileService.java
- src/main/java/backend/sculptor/domain/stone/controller/StoneController.java
- src/main/java/backend/sculptor/domain/stone/service/StoneService.java
- src/main/java/backend/sculptor/domain/user/controller/UserController.java
- src/main/java/backend/sculptor/domain/user/entity/Users.java
- src/main/java/backend/sculptor/domain/user/service/UserService.java
- src/main/java/backend/sculptor/global/exception/GlobalExceptionHandler.java
- src/main/java/backend/sculptor/global/exception/InvalidRequestException.java
---
사용자의 대표 돌 설정 로직 추가
---
---
#62
> [feat] 대표 돌 설정, 공방 돌 삭제 로직 추가

- src/main/java/backend/sculptor/domain/stone/service/StoneService.java
- src/main/java/backend/sculptor/domain/user/controller/UserController.java
- src/main/java/backend/sculptor/domain/user/service/UserService.java
구매내역 조회 로직의 에러 수정
---
구매내역 조회 로직에 에러가 있어서 수정했습니다.
---
kimin
---
> [fix] 구매내역 조회 에러 수정

- src/main/java/backend/sculptor/domain/follow/service/FollowService.java
팔로잉중인 사용자의 대표돌 조회 로직 에러 수정
---
팔로잉하는 사용자들의 대표 돌을 조회하는 로직에서 에러를 수정했습니다!
---
kimin
---
> [fix] 팔로잉중인 사용자의 대표돌 조회 로직 에러 수정

- src/main/java/backend/sculptor/domain/comment/entity/Comment.java
- src/main/java/backend/sculptor/domain/museum/service/MuseumDetailService.java
- src/main/java/backend/sculptor/domain/user/service/UserService.java
> [feat] 박물관 상세페이지 대표 돌 정보 반환

- src/main/java/backend/sculptor/domain/home/controller/HomeController.java
- src/main/java/backend/sculptor/domain/home/dto/UserRepresentStone.java
- src/main/java/backend/sculptor/domain/stone/service/StoneService.java
> [feat] 나의 대표 돌 조회 로직 추가

- .github/workflows/deploy.yml
> [deploy] ci

- .ebextensions-dev/00-makefiles.config
- .ebextensions-dev/01-set-timezone.config
- .github/workflows/deploy.yml
- .platforms/nginx.conf
- Procfile
- build.gradle
- src/main/java/backend/sculptor/domain/health/HealthCheckController.java
> [deploy] ci/cd 파이프라인 구축

- src/main/java/backend/sculptor/domain/museum/service/MuseumProfoileService.java
- src/main/java/backend/sculptor/domain/museum/service/MuseumService.java
- src/main/java/backend/sculptor/domain/stone/service/StoneService.java
- src/main/java/backend/sculptor/domain/store/controller/StoreController.java
- src/main/java/backend/sculptor/domain/store/dto/StoreStones.java
- src/main/java/backend/sculptor/domain/store/service/StoreService.java
> [feat] 나의 돌 조회 구현

- src/main/java/backend/sculptor/domain/stone/entity/Stone.java
- src/main/java/backend/sculptor/domain/stone/entity/StoneItem.java
- src/main/java/backend/sculptor/domain/stone/repository/ItemRepository.java
- src/main/java/backend/sculptor/domain/stone/repository/StoneItemRepository.java
- src/main/java/backend/sculptor/domain/stone/service/AchieveService.java
- src/main/java/backend/sculptor/domain/stone/service/ItemService.java
- src/main/java/backend/sculptor/domain/stone/service/StoneService.java
- src/main/java/backend/sculptor/domain/store/controller/StoreController.java
- src/main/java/backend/sculptor/domain/store/dto/Basket.java
- src/main/java/backend/sculptor/domain/store/dto/Purchase.java
- src/main/java/backend/sculptor/domain/store/dto/StoreStones.java
- src/main/java/backend/sculptor/domain/store/dto/WearItem.java
- src/main/java/backend/sculptor/domain/store/service/StoreService.java
- src/main/java/backend/sculptor/domain/user/entity/Users.java
- src/main/java/backend/sculptor/global/exception/ErrorCode.java
> [feat] 돌 아이템 착용, 장바구니 조회, 아이템 구매 로직 추가

- src/main/resources/application.yml
> [feat] 지원되지 않는 url 예외처리

- src/main/java/backend/sculptor/domain/home/controller/HomeController.java
> [feat] 팔로잉 정보 DTO 수정

- src/main/java/backend/sculptor/domain/home/controller/HomeController.java
> [feat] 팔로잉 유저 정보 상세 조회 리턴 타입 리스트에서 객체로 변경

- src/main/java/backend/sculptor/domain/home/controller/HomeController.java
- src/main/java/backend/sculptor/domain/home/dto/FollowingRepresentStone.java
- src/main/java/backend/sculptor/domain/stone/service/AchieveService.java
> [feat] 팔로잉 유저 상세 정보 조회 시 대표 돌로 조회, 팔로잉 여부 추가

- src/main/java/backend/sculptor/domain/home/controller/HomeController.java
- src/main/java/backend/sculptor/domain/home/dto/FollowingRepresentStone.java
> [feat] 팔로잉 유저 정보 상세 조회 프로필 이미지 추가

- src/main/java/backend/sculptor/domain/store/controller/StoreController.java
- src/main/java/backend/sculptor/domain/store/dto/MoneyDTO.java
- src/main/java/backend/sculptor/domain/store/service/StoreService.java
> [feat]돌 powder 조회 로직 생성

- src/main/java/backend/sculptor/domain/user/controller/UserController.java
사용자 세션 만료시간 설정
---
사용자 로그인시 설정되는 세션이 만료되지 않도록 설정했습니다.
---
kimin
---
> [fix] 사용자 로그인된 세션 만료시간 설정

- src/main/java/backend/sculptor/domain/stone/entity/Stone.java
- src/main/java/backend/sculptor/domain/stone/entity/StoneItem.java
- src/main/java/backend/sculptor/domain/stone/service/ItemService.java
- src/main/java/backend/sculptor/domain/store/controller/StoreController.java
- src/main/java/backend/sculptor/domain/store/dto/Basket.java
- src/main/java/backend/sculptor/domain/store/dto/Purchase.java
- src/main/java/backend/sculptor/domain/store/dto/StoreItemDTO.java
- src/main/java/backend/sculptor/domain/store/dto/WearItem.java
- src/main/java/backend/sculptor/domain/store/dto/WearType.java
- src/main/java/backend/sculptor/domain/store/service/StoreService.java
> #76 [feat] 아이템 -> 원석으로 변경

- src/main/java/backend/sculptor/domain/store/dto/StoreStones.java
- src/main/java/backend/sculptor/domain/store/service/StoreService.java
> #76 [feat] 상점 조각상 조회 카테고리 추가

- src/main/java/backend/sculptor/domain/store/controller/StoreController.java
> [chore] 장바구니 조회 http 메서드 변경

- src/main/java/backend/sculptor/domain/stone/controller/StoneController.java
> [refact] 조회된 돌 정보 없을때 200 & 빈 배열로 수정

- src/main/java/backend/sculptor/domain/stone/service/StoneService.java
- src/main/java/backend/sculptor/domain/store/controller/StoreController.java
- src/main/java/backend/sculptor/domain/store/service/StoreService.java
> [feat] 구매한 아이템 조회 로직 변경

- src/main/java/backend/sculptor/domain/stone/entity/StoneItem.java
StoneItem 엔티티 외래키 관련 수정
---
---
kimin
---
> [fix] StoneItem 엔티티 외래키 관련 수정
